platform :ios, '10.0'

target 'RxUnfurl_Example' do
	use_frameworks!

  	pod 'RxUnfurl', :path => '../'
  	pod 'RxSwift'
  	pod 'Alamofire'

  	target 'RxUnfurl_Tests' do
    	inherit! :search_paths
  	end
end
